/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessTokens: () => import('#controllers/access_tokens_controller'),
  EmailVerifications: () => import('#controllers/email_verifications_controller'),
  FacebookAuth: () => import('#controllers/facebook_auth_controller'),
  GoogleAuth: () => import('#controllers/google_auth_controller'),
  Health: () => import('#controllers/health_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  PasswordResets: () => import('#controllers/password_resets_controller'),
  Profile: () => import('#controllers/profile_controller'),
}
