/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class BottleSourceSchema extends BaseModel {
  static $columns = ['bottleId', 'createdAt', 'externalId', 'id', 'lastSyncedAt', 'rawHash', 'source'] as const
  $columns = BottleSourceSchema.$columns
  @column()
  declare bottleId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare externalId: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastSyncedAt: DateTime
  @column()
  declare rawHash: string | null
  @column()
  declare source: string
}

export class BottleSchema extends BaseModel {
  static $columns = ['abv', 'attrs', 'barcode', 'brand', 'categoryId', 'createdAt', 'deletedAt', 'id', 'name', 'origin', 'photoUrl', 'updatedAt', 'volumeMl'] as const
  $columns = BottleSchema.$columns
  @column()
  declare abv: string | null
  @column()
  declare attrs: any
  @column()
  declare barcode: string | null
  @column()
  declare brand: string | null
  @column()
  declare categoryId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare origin: string | null
  @column()
  declare photoUrl: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare volumeMl: number | null
}

export class CategorySchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'name', 'slug', 'updatedAt'] as const
  $columns = CategorySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare slug: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class FriendshipSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'status', 'updatedAt', 'userAId', 'userBId'] as const
  $columns = FriendshipSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userAId: number
  @column()
  declare userBId: number
}

export class MessageSchema extends BaseModel {
  static $columns = ['body', 'createdAt', 'id', 'readAt', 'receiverId', 'senderId'] as const
  $columns = MessageSchema.$columns
  @column()
  declare body: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare readAt: DateTime | null
  @column()
  declare receiverId: number
  @column()
  declare senderId: number
}

export class ReportSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'reason', 'reporterId', 'targetId', 'targetType'] as const
  $columns = ReportSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare reason: string
  @column()
  declare reporterId: number
  @column()
  declare targetId: string
  @column()
  declare targetType: string
}

export class SubscriptionSchema extends BaseModel {
  static $columns = ['createdAt', 'currentPeriodEnd', 'id', 'plan', 'provider', 'providerCustomerId', 'providerSubscriptionId', 'status', 'updatedAt', 'userId'] as const
  $columns = SubscriptionSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare currentPeriodEnd: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare plan: string
  @column()
  declare provider: string
  @column()
  declare providerCustomerId: string | null
  @column()
  declare providerSubscriptionId: string | null
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class UserBottleSchema extends BaseModel {
  static $columns = ['abvOverride', 'attrsOverride', 'bottleId', 'boughtAt', 'brandOverride', 'createdAt', 'id', 'isPublic', 'nameOverride', 'note', 'originOverride', 'photoUrlOverride', 'pricePaid', 'review', 'updatedAt', 'userId', 'volumeMlOverride'] as const
  $columns = UserBottleSchema.$columns
  @column()
  declare abvOverride: string | null
  @column()
  declare attrsOverride: any | null
  @column()
  declare bottleId: number
  @column()
  declare boughtAt: string | null
  @column()
  declare brandOverride: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isPublic: boolean
  @column()
  declare nameOverride: string | null
  @column()
  declare note: string | null
  @column()
  declare originOverride: string | null
  @column()
  declare photoUrlOverride: string | null
  @column()
  declare pricePaid: string | null
  @column()
  declare review: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
  @column()
  declare volumeMlOverride: number | null
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'emailVerified', 'fullName', 'id', 'image', 'isPublic', 'password', 'pseudo', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare emailVerified: boolean
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare image: string | null
  @column()
  declare isPublic: boolean
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare pseudo: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
